### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by kartikmohta** [KumarRobotics/bluefox2#10]
Just a reminder to fix the travis build failure.

**Comment by kartikmohta** [comment]
Now that they have a trusty option, can we re-enable this? http://docs.travis-ci.com/user/trusty-ci-environment/

**Comment by versatran01** [comment]
Cool. If you don't mind setting it up :smile: otherwise I will do it after I come back.

**Comment by kartikmohta** [comment]
Has been fixed for a while now, since 8321aae718b0a6a6593035961b470486370ac16d
