### ISSUE TITLE
Is it possible for this package to load ATAN calibration file?

### ISSUE THREAD

**Issue by ziyangli** [KumarRobotics/bluefox2#12]
According to https://github.com/uzh-rpg/rpg_svo/wiki/Camera-Calibration, we can calibrate this camera via ATAN model, and their calibration file looks like this https://github.com/uzh-rpg/rpg_svo/blob/master/svo_ros/param/camera_atan.yaml, which is different from the normal one.

So is it possible for this package to load their calibration file?

Look forward to your answer!

Best,

Ziyang

**Comment by versatran01** [comment]
The bluefox2 package will load any file as long as it is valid sensor_msgs/CameraInfo.
A simple and quick hack is to just modify your calibration yaml file, maybe put the d0 parameter as the first and only element of D.

**Comment by sunghoon031** [comment]
Or you can use https://github.com/uzh-rpg/rpg_svo/blob/master/svo_ros/param/camera_pinhole.yaml instead. Although in my case, the provided calibration values didn't quite work, so I had to recalibrate anyways...
