### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by justinthomas** [KumarRobotics/bluefox2#15]
I'm receive the following error when compiling on an ODROID Xu3 running Ubuntu 14.04:

In file included from /home/odroid/catkin_ws/src/bluefox2/src/bluefox2_ros.cpp:1:0:
/home/odroid/catkin_ws/src/bluefox2/include/bluefox2/bluefox2_ros.h:17:8: error: ‘bool bluefox2::Bluefox2Ros::Grab(const ImagePtr&)’ marked override, but does not override
   bool Grab(const sensor_msgs::ImagePtr& image_msg) override;
        ^

**Comment by versatran01** [comment]
I made some small changes to camera_base and didn't upgrade bluefox2.
I should be fixed now

**Comment by justinthomas** [comment]
Perfect, that did the trick. Thanks!
