### ISSUE TITLE
Auto exposure control

### ISSUE THREAD

**Issue by nicolov** [KumarRobotics/bluefox2#16]
Hi, thanks for the great work. According to the readme, there are 4 possibile aec settings, two of which are controlled by the driver. On the other hand, the implementation seems to treat the setting as a bool, and I can't seem to find any reference to those two driver-controlled modes in the code.

Thanks,
Nico

**Comment by versatran01** [comment]
My bad, forgot to update the readme. For now just follow the cfg file, I will update readme later.
I removed support for `aec_fixed` and `aec_clamped` as I found them not really useful in experiments and usually causes confusion.

**Comment by nicolov** [comment]
Thanks. If anyone is interested, there's some code in commit 03cced3.
