### ISSUE TITLE
Unable to locate mvimpact_acquire.git repository

### ISSUE THREAD

**Issue by atulyashivamshree** [KumarRobotics/bluefox2#18]
I was trying to install the mvIMPACT_Acquire SDK using the install.bash script inside the install folder. However the error which I get on running the script is `fatal: repository 'https://github.com/versatran01/mvimpact_acquire.git/' not found`

**Comment by versatran01** [comment]
There is no need to use the install.bash. 
The recommended way is to install the sdk from matrix-vision website.
I will remove that script and update the readme.

**Comment by h3ct0r** [comment]
Hi, @versatran01 the readme and script are still pointing to your repository!

**Comment by versatran01** [comment]
@h3ct0r I will fix it. Thanks for pointing it out.
