### ISSUE TITLE
how to install the bluefox2 driver ? 

### ISSUE THREAD

**Issue by kirill-ros** [KumarRobotics/bluefox2#20]
hallo, 
I am new in ROS. 
I am trying to publish images with my mvBlueFOX MLC200wG using bluefox2 driver (Ubuntu 14.04 with ROS Indigo). 
I did the following: 

cd catkin_ws/src git clone https://github.com/KumarRobotics/bluefox2.git
cd ..
catkin_make

After that i get an error: 
____________________________________________________________________
  Could not find a package configuration file provided by "camera_base" with
  any of the following names:

    camera_baseConfig.cmake
    camera_base-config.cmake

  Add the installation prefix of "camera_base" to CMAKE_PREFIX_PATH or set
  "camera_base_DIR" to a directory containing one of the above files.  If
  "camera_base" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  bluefox2/CMakeLists.txt:7 (find_package)

-- Could not find the required component 'camera_base'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "camera_base" with
  any of the following names:

    camera_baseConfig.cmake
    camera_base-config.cmake

  Add the installation prefix of "camera_base" to CMAKE_PREFIX_PATH or set
  "camera_base_DIR" to a directory containing one of the above files.  If
  "camera_base" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  bluefox2/CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/kirill/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/kirill/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
__________________________________________________________________________

Could someone help me please? What am I doing wrong?
What are the next steps to start the single node?
Thank you in advance!

**Comment by kirill-ros** [comment]
thank you very much for your answer!
you had right, that was necessary. I have also installed the native driver from matrixvision: ./install_mvBlueFOX.sh (mvBlueFOX-x86_ABI2-2.16.1.tgz) for 32bit system. 
But now I have a new error: 
______________________________________________________________________________
Base path: /home/kirill/catkin_ws
Source space: /home/kirill/catkin_ws/src
Build space: /home/kirill/catkin_ws/build
Devel space: /home/kirill/catkin_ws/devel
Install space: /home/kirill/catkin_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/kirill/catkin_ws/build"
####
####
#### Running command: "make -j2 -l2" in "/home/kirill/catkin_ws/build"
####
[  0%] Built target _svo_msgs_generate_messages_check_deps_NbvTrajectory
[  0%] Built target _svo_msgs_generate_messages_check_deps_Feature
[  0%] Built target _svo_msgs_generate_messages_check_deps_DenseInput
[  0%] Built target _svo_msgs_generate_messages_check_deps_Info
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] [  0%] Built target sensor_msgs_generate_messages_cpp
Built target geometry_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  1%] Built target intuitiver_joystick
[  2%] Built target intuitiver_joystick_node
[  2%] Built target std_msgs_generate_messages_py
[  2%] Built target _ptam_com_generate_messages_check_deps_KeyFrame_srv
[  2%] Built target _ptam_com_generate_messages_check_deps_OctoMapPointStamped
[  2%] Built target _ptam_com_generate_messages_check_deps_Vector3Array
[  2%] [  2%] Built target _ptam_com_generate_messages_check_deps_KeyFrame_msg
Built target _ptam_com_generate_messages_check_deps_PointCloud
[  2%] [  2%] Built target _ptam_com_generate_messages_check_deps_ptam_info
Built target _ptam_com_generate_messages_check_deps_OctoMapScan
[  2%] Built target std_msgs_generate_messages_lisp
[  2%] Built target std_msgs_generate_messages_cpp
[  2%] Built target _ptam_com_generate_messages_check_deps_OctoMapPointArray
[  3%] Built target bluefox2_gencfg
[  8%] Built target rqt_ptam
[  8%] Built target roscpp_generate_messages_cpp
[  8%] Built target roscpp_generate_messages_lisp
[  8%] Built target _bluefox2_generate_messages_check_deps_SetExposeSrv
[  8%] Built target roscpp_generate_messages_py
[  8%] Built target rosgraph_msgs_generate_messages_lisp
[  8%] Built target rosgraph_msgs_generate_messages_cpp
[  8%] Built target rosgraph_msgs_generate_messages_py
[  8%] Built target diagnostic_msgs_generate_messages_cpp
[  8%] Built target diagnostic_msgs_generate_messages_lisp
[  8%] Built target dynamic_reconfigure_generate_messages_lisp
[  8%] Built target dynamic_reconfigure_generate_messages_cpp
[  8%] Built target dynamic_reconfigure_gencfg
[  8%] Built target dynamic_reconfigure_generate_messages_py
[  8%] Built target diagnostic_msgs_generate_messages_py
[  8%] Built target nodelet_generate_messages_py
[  8%] Built target nodelet_generate_messages_lisp
[  8%] Built target nodelet_generate_messages_cpp
[  8%] Built target bond_generate_messages_cpp
[  8%] Built target bond_generate_messages_lisp
[  8%] Built target bond_generate_messages_py
Building all dependencies
make[3]: Warnung: Kein Jobserver verfügbar: -j1 wird gesetzt. »+« zur Ursprungsregel
hinzufügen.
making third party libs
[  9%] Built target ptam_gencfg
[  9%] Built target usb_cam
[ 16%] Built target vikit_common
-- Configuring done
[ 20%] Built target svo_msgs_generate_messages_py
CMake Warning (dev) at CMakeLists.txt:17 (add_library):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "agast" links to some libraries for which the linker must
  search:

    dl, m, pthread, rt, tbb

  and other libraries with known full path:

    /usr/local/lib/libopencv_viz.so.2.4.9
    /usr/lib/i386-linux-gnu/libGLU.so

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/kirill/catkin_ws/src/ethzasl_ptam/ptam/thirdparty/agast/build
[ 23%] Built target svo_msgs_generate_messages_cpp
[ 26%] Built target svo_msgs_generate_messages_lisp
[100%] Built target agast
[ 33%] Built target ptam_com_generate_messages_py
[ 33%] Built target DEPS
[ 45%] [ 45%] Built target ptam_com_generate_messages_lisp
Built target ptam_com_generate_messages_cpp
[ 46%] Built target bluefox2_generate_messages_lisp
[ 48%] Built target bluefox2_generate_messages_py
[ 48%] Built target bluefox2_generate_messages_cpp
[ 54%] Built target cameracalibrator
[ 55%] Built target ptam_visualizer
[ 69%] Built target ptam
[ 70%] Built target remote_ptam
[ 71%] Built target usb_cam_node
[ 73%] [ 73%] Built target test_vk_common_patch_score
Built target test_vk_common_camera
[ 74%] Built target test_vk_common_triangulation
[ 75%] Built target vikit_ros
[ 75%] [ 75%] Built target svo_msgs_generate_messages
Built target ptam_com_generate_messages
[ 75%] [ 75%] Built target bluefox2_gencpp
Built target bluefox2_generate_messages
[ 81%] Built target bluefox2
Linking CXX executable /home/kirill/catkin_ws/devel/lib/bluefox2/bluefox2_list_cameras
[ 91%] Built target svo
Linking CXX executable /home/kirill/catkin_ws/devel/lib/bluefox2/bluefox2_multi_node
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::ComponentAccess::compGetStringParam(mvIMPACT::acquire::TOBJ_StringQuery, int, int) const':
list_cameras.cpp:(.text._ZNK8mvIMPACT7acquire15ComponentAccess18compGetStringParamENS0_16TOBJ_StringQueryEii[_ZNK8mvIMPACT7acquire15ComponentAccess18compGetStringParamENS0_16TOBJ_StringQueryEii]+0x47): Nicht definierter Verweis auf `OBJ_GetSWithInplaceConstruction'
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::ComponentAccess::ComponentAccess(int)':
list_cameras.cpp:(.text._ZN8mvIMPACT7acquire15ComponentAccessC2Ei[_ZN8mvIMPACT7acquire15ComponentAccessC5Ei]+0x2b): Nicht definierter Verweis auf `OBJ_CheckHandle'
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::ComponentAccess::changedCounter() const':
list_cameras.cpp:(.text._ZNK8mvIMPACT7acquire15ComponentAccess14changedCounterEv[_ZNK8mvIMPACT7acquire15ComponentAccess14changedCounterEv]+0x18): Nicht definierter Verweis auf `OBJ_GetChangedCounter'
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::Component::isValid() const':
list_cameras.cpp:(.text._ZNK8mvIMPACT7acquire9Component7isValidEv[_ZNK8mvIMPACT7acquire9Component7isValidEv]+0x18): Nicht definierter Verweis auf `OBJ_CheckHandle'
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::Component::type() const':
list_cameras.cpp:(.text._ZNK8mvIMPACT7acquire9Component4typeEv[_ZNK8mvIMPACT7acquire9Component4typeEv]+0x18): Nicht definierter Verweis auf `OBJ_GetType'
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::ComponentLocatorBase::bindSearchBase(int, std::string const&)':
list_cameras.cpp:(.text._ZN8mvIMPACT7acquire20ComponentLocatorBase14bindSearchBaseEiRKSs[_ZN8mvIMPACT7acquire20ComponentLocatorBase14bindSearchBaseEiRKSs]+0x5d): Nicht definierter Verweis auf `OBJ_GetHandleEx'
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::ComponentLocatorBase::findComponent(std::string const&, int, int) const':
list_cameras.cpp:(.text._ZNK8mvIMPACT7acquire20ComponentLocatorBase13findComponentERKSsii[_ZNK8mvIMPACT7acquire20ComponentLocatorBase13findComponentERKSsii]+0x35): Nicht definierter Verweis auf `OBJ_GetHandleEx'
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::Property::readS(int, std::string const&) const':
list_cameras.cpp:(.text._ZNK8mvIMPACT7acquire8Property5readSEiRKSs[_ZNK8mvIMPACT7acquire8Property5readSEiRKSs]+0x90): Nicht definierter Verweis auf `OBJ_GetSFormattedEx'
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::Device::open()':
list_cameras.cpp:(.text._ZN8mvIMPACT7acquire6Device4openEv[_ZN8mvIMPACT7acquire6Device4openEv]+0x1e): Nicht definierter Verweis auf `DMR_OpenDevice'
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::DeviceManager::updateInfoVector() const':
list_cameras.cpp:(.text._ZNK8mvIMPACT7acquire13DeviceManager16updateInfoVectorEv[_ZNK8mvIMPACT7acquire13DeviceManager16updateInfoVectorEv]+0x68): Nicht definierter Verweis auf `DMR_GetDeviceCount'
list_cameras.cpp:(.text._ZNK8mvIMPACT7acquire13DeviceManager16updateInfoVectorEv[_ZNK8mvIMPACT7acquire13DeviceManager16updateInfoVectorEv]+0xb3): Nicht definierter Verweis auf `DMR_GetDevice'
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::DeviceManager::DeviceManager()':
list_cameras.cpp:(.text._ZN8mvIMPACT7acquire13DeviceManagerC2Ev[_ZN8mvIMPACT7acquire13DeviceManagerC5Ev]+0x46): Nicht definierter Verweis auf `DMR_Init'
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::DeviceManager::~DeviceManager()':
list_cameras.cpp:(.text._ZN8mvIMPACT7acquire13DeviceManagerD2Ev[_ZN8mvIMPACT7acquire13DeviceManagerD5Ev]+0x1b): Nicht definierter Verweis auf `DMR_Close'
CMakeFiles/bluefox2_list_cameras.dir/list_cameras.cpp.o: In Funktion `mvIMPACT::acquire::EnumPropertyI<int>::read(int) const':
list_cameras.cpp:(.text._ZNK8mvIMPACT7acquire13EnumPropertyIIiE4readEi[_ZNK8mvIMPACT7acquire13EnumPropertyIIiE4readEi]+0x1f): Nicht definierter Verweis auf `OBJ_GetI'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/kirill/catkin_ws/devel/lib/bluefox2/bluefox2_list_cameras] Fehler 1
make[1]: *** [bluefox2/src/CMakeFiles/bluefox2_list_cameras.dir/all] Fehler 2
make[1]: *** Auf noch nicht beendete Prozesse wird gewartet …
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_ImageRequestReset'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetType'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetI'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_AllocImageRequestBufferDesc'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_GetDevice'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_Close'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetF'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetFlags'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_OpenDevice'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetElementCount'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_ReleaseImageBuffer'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_ReleaseImageRequestBufferDesc'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_SetF'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_GetDriverHandle'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetFirstChild'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetFDictEntries'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_GetDeviceCount'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetDictSize'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetChangedCounter'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_ErrorCodeToString'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetP'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_CloseDevice'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetIDictEntries'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_ImageRequestUnlock'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_SetI'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_FindList'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_Init'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_ImageRequestWaitFor'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetHandleEx'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_IsConstantDefined'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetNextSibling'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetSFormattedEx'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_GetSWithInplaceConstruction'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `DMR_ImageRequestSingle'
/home/kirill/catkin_ws/devel/lib/libbluefox2.so: Nicht definierter Verweis auf `OBJ_CheckHandle'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/kirill/catkin_ws/devel/lib/bluefox2/bluefox2_multi_node] Fehler 1
make[1]: *** [bluefox2/src/CMakeFiles/bluefox2_multi_node.dir/all] Fehler 2
make: *** [all] Fehler 2
Invoking "make -j2 -l2" failed
_______________________________________________________________________________

Do you have an idea? 
Thanks again!

**Comment by versatran01** [comment]
Try cleaning the workspace and rebuild.
