### ISSUE TITLE
how to start the bluefox2 driver?

### ISSUE THREAD

**Issue by kirill-ros** [KumarRobotics/bluefox2#21]
hello, 
I am using the bluefox cam (mvBlueFox-mlc 200 wG; ROS Indigo, Ubuntu 14.04.) and trying to start the single_node.launch file by typing:

roslaunch bluefox2 single_node.launch

after that I get following: 
_____________________________________________________________________________
... logging to /home/kirill/.ros/log/64cc48dc-4f3b-11e6-b816-b8aeed718e60/roslaunch-kirill-boschnuc-4678.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

arg 'device' is not defined. 

Arg xml is <arg default="$(arg device)" name="serial"/>
The traceback for the exception was written to the log file
______________________________________________________________________________

I suppose I have to change the single_node.launch file and to add the serial number of the camera (in my case: mv_25001846). But I have no idea where exactly the serial number should be placed. 
Is there something else what should be done?

Thanks for your help!

P.S. the native driver of the matrix vision cam was installed. 
After typing catkin_make there are no errors.

**Comment by versatran01** [comment]
```
roslaunch bluefox2 single_node.launch device:=your serial number here.
```
If you are not sure what your camera's serial number is, put 0 there and it will show up in the error print out.
