### ISSUE TITLE
Compilation possible on Jetson TX2?

### ISSUE THREAD

**Issue by sahsuvar** [KumarRobotics/bluefox2#27]
Hey there, we use a Nvidia Jetson TX2 board which runs on an AArch64 architecture. Is it possible to compile this driver for this architecture? 
Thanks in advance

**Comment by versatran01** [comment]
Have you tried?

**Comment by sahsuvar** [comment]
Yes I've tried compiling it and the target fails at **Linking CXX executable /home/nvidia/catkin_ws/devel/lib/bluefox2/bluefox2_list_cameras**

the last bit of the building log, when the error starts:

[fehlerlog.txt](https://github.com/KumarRobotics/bluefox2/files/1484570/fehlerlog.txt)

**Comment by versatran01** [comment]
Try install the arm version sdk from matrix vision and compile against that.

**Comment by sahsuvar** [comment]
I already installed that arm driver. It resides in /opt/ and works for c++ programs etc. but apparently not for the compilation with the ROS-Driver.

**Comment by versatran01** [comment]
I think the driver by default links to the binaries that comes with it. Could you try to force it to link to the one you installed?

**Comment by sahsuvar** [comment]
Hey, i found the problem. 

In file ~/catkin_ws/src/bluefox2/cmake/FindmvIMPACT.cmake 

The script searches for the library with "uname -m". Apparently the Jetson TX2 outputs "aarch64" with this command. Looking at "/opt/mvIMPACT_acquire/lib" the name of the directory is "arm64". When you install the driver for arm-based devices, the directory get's named "arm64". That's why the script couldn't find the corresponding library path. A simple rename to "aarch64" in "/opt/mvIMPACT_acquire/lib/" from "arm64" solves the problem for me.

Thanks for your help though!

**Comment by Pateman16** [comment]
Hello sahsuvar! 

I have the same problem as you do and have tried to do your solution and also hardcoded arm64 in the cmake file instead of the result of uname -m but no luck, the problem remains, could you give a bit more detailed explanation of how you did it? Thanks in advance

**Comment by indigomega** [comment]
@Pateman16 could you give a log of your error?

**Comment by sahsuvar** [comment]
@Pateman16 Hey, sorry for the more than late answer: I simply renamed the driver folder to the name, which is given by the command "uname -m". So "/opt/mvIMPACT_acquire/lib/arm64" becomes "/opt/mvIMPACT_acquire/lib/aarch64". At least on the Jetson TX2.

**Comment by kartikmohta** [comment]
I've added the arm64 libraries in the package itself with the correct folder name. This should work out of the box now.

**Comment by wdeyes** [comment]
Hello！
I still have this error. Who is successful on tx2 ?
