### ISSUE TITLE
rostopic echo compressedDepth error

### ISSUE THREAD

**Issue by HarrrrryLi** [KumarRobotics/bluefox2#29]
When I'm trying to echo compressedDepth(after launching stereo_node.launch). I shows there is an error shown as following. I wonder how to solve this problem.

> Compressed Depth Image Transport - Compression requires single-channel 32bit-floating point or 16bit raw depth images (input format is: bgra8).

**Comment by versatran01** [comment]
We don't publish depth image at all, the only outputs are 2 images and 2 camera infos.
