### ISSUE TITLE
single_node launch error

### ISSUE THREAD

**Issue by arkinrc** [KumarRobotics/bluefox2#31]
Hello everyone, 
Firstly thanks to author mr.kumar for this kind of great work. well, i am using this repository for my camera mlc200wG. after installation of driver and this repository there is error while launching the single_node.launch file. i have provided the required configuration according to my camera serial number etc. the error is given below.

auto-starting new master
process[master]: started with pid [5241]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b4e163c2-5c38-11e9-96b9-00044b8d3c24
process[rosout-1]: started with pid [5254]
started core service [/rosout]
process[mv_25002830-2]: started with pid [5271]
process[mpu6050_serial_to_imu_node-3]: started with pid [5272]
terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast
[mv_25002830-2] process has died [pid 5271, exit code -6, cmd /home/nvidia/catkin_ws/devel/lib/bluefox2/bluefox2_single_node __name:=mv_25002830 __log:=/home/nvidia/.ros/log/b4e163c2-5c38-11e9-96b9-00044b8d3c24/mv_25002830-2.log].
log file: /home/nvidia/.ros/log/b4e163c2-5c38-11e9-96b9-00044b8d3c24/mv_25002830-2*.log

it seems something related with std::bad_cast error on the other hand singl_nodelet.launch is working well on my system. kindly help me to figure out this issue. thanks alot

**Comment by versatran01** [comment]
It is recommended that you install the mvImpact sdk from their website instead of using the one provided in the repo. 
https://www.matrix-vision.com/programming-interface-mvimpact-acquire.html

**Comment by arkinrc** [comment]
> It is recommended that you install the mvImpact sdk from their website instead of using the one provided in the repo.
> https://www.matrix-vision.com/programming-interface-mvimpact-acquire.html

thanks for your prompt feedback. I have already installed this sdk. I also tested this all, on my nvidia jetson tx2 which was working well. but recently, i have to re-flash the whole system and rebuild this all setup. but now its not working and showing that above error. looking for your feedback. thanks

**Comment by versatran01** [comment]
if you can plug your tx2 into a monitor, then try to open the camera from the official app see if that works.

**Comment by arkinrc** [comment]
> if you can plug your tx2 into a monitor, then try to open the camera from the official app see if that works.



my tx2 is connected with monitor and it can work with wxPropView app.  But when i try to use ros package of bluefox2 then it show the above error. I tried this with ubuntu 16.04 on my laptop and its working properly using official app as well as ros package. Any other suggestions? Thanks

**Comment by arkinrc** [comment]
Moreover, there isn't any issue of permission/ udev. I have already added udev file into desired location but still the same error.

**Comment by versatran01** [comment]
I don't have a tx2 nor an mv camera at my hand currently so I cannot try and reproduce this. If single_nodelet is working fine can you just work with that?

**Comment by arkinrc** [comment]
> I don't have a tx2 nor an mv camera at my hand currently so I cannot try and reproduce this. If single_nodelet is working fine can you just work with that?

Thanks.. the issue was why single_node is not working and i resolved that issue after spending few days on that. Again thanks for your prompt reply and concentration on this issue.

**Comment by Lwenqi** [comment]
Hi arkinrc. I have encountered the same error when running on tx2. Can I know how do you solve this issues? Thank you very much.

**Comment by IeiuniumLux** [comment]
@arkinrc can you please provide more details on how you got single_node working?
