### ISSUE TITLE
stereo node synchronization

### ISSUE THREAD

**Issue by kvmanohar22** [KumarRobotics/bluefox2#33]
I want to run bluefox2 with two cameras and synchronization is quite important. From the README it is clear that there are two methods that can be employed to achieve this.
1. Using master-slave method
2. By hardwiring the same trigger source to both the cameras.

My doubt is, looking at the current implementation, it was not quite clear to me what is employed. Also, I couldn't find any parameters in the stereo_node.launch file that allows me to choose one method over the other

I presume, if used as master-slave, then, I wouldn't require to hardwire the same trigger source to both  the cameras.

**Comment by versatran01** [comment]
If I remember correctly, the default is using software trigger.
It is possible to do hardware trigger, search ctm in bluefox.cpp.

**Comment by kvmanohar22** [comment]
Yes, I am using hardware trigger by setting `ctm=-1` Looks like the two cameras behave in master-slave mode although I have to connect the same trigger line to both the cameras.

It's working now!

**Comment by versatran01** [comment]
Good to know
